<a href="https://colab.research.google.com/github/kumar-mahendra/66DaysOfData/blob/main/Natural_Language_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NLP

## Word Tokenization, padding, Removing Stopwords and Cleaning Data

#### Dated : 26-01-2021

In [ ]:

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:

tokenizer = Tokenizer(num_words=100,oov_token="<oov>")  #oov means out_of_vocabulory text which will replace any irrelevent word or word which is new or not known to 
                                                        # model as "<oov>"(here you can take any string but make sure its not in your sequence)

#sample input , a list of sentences 
sentences = ['I am Mahendra Kumar!!!', 'I am currently in my second year of study,at "IIT Goa".','My branch is maths & computing','Want to become a data scientist.','some random stuff xjksdj skdjfs skdjf']

#Lets start 
tokenizer.fit_on_texts(sentences)  
word_index = tokenizer.word_index
print(word_index)

{'<oov>': 1, 'i': 2, 'am': 3, 'my': 4, 'mahendra': 5, 'kumar': 6, 'currently': 7, 'in': 8, 'second': 9, 'year': 10, 'of': 11, 'study': 12, 'at': 13, 'iit': 14, 'goa': 15, 'branch': 16, 'is': 17, 'maths': 18, 'computing': 19, 'want': 20, 'to': 21, 'become': 22, 'a': 23, 'data': 24, 'scientist': 25, 'some': 26, 'random': 27, 'stuff': 28, 'xjksdj': 29, 'skdjfs': 30, 'skdjf': 31}


In [ ]:
#generate sequences corresponding to input 
sequences = tokenizer.texts_to_sequences(sentences)
print(*sequences,sep='\n')


[2, 3, 5, 6]
[2, 3, 7, 8, 4, 9, 10, 11, 12, 13, 14, 15]
[4, 16, 17, 18, 19]
[20, 21, 22, 23, 24, 25]
[26, 27, 28, 29, 30, 31]


In [ ]:

#generally we fed data in model having same shapes which is not there so we use padding to achive that 

padded_sequences = pad_sequences(sequences)
print("Padding with default settings :")
print(*padded_sequences,sep='\n')

padded_sequences = pad_sequences(sequences,maxlen=6)
print("\nPadding with maxlen parameter :")
print(*padded_sequences,sep='\n')

padded_sequences = pad_sequences(sequences,maxlen=6,padding='post')
print("\nPadding with maxlen & post_padding technique :")
print(*padded_sequences,sep='\n')

padded_sequences = pad_sequences(sequences,maxlen=6,padding='post',truncating='post')
print("\nPadding with above two + truncating settings :")
print(*padded_sequences,sep='\n')


Padding with default settings :
[0 0 0 0 0 0 0 0 2 3 5 6]
[ 2  3  7  8  4  9 10 11 12 13 14 15]
[ 0  0  0  0  0  0  0  4 16 17 18 19]
[ 0  0  0  0  0  0 20 21 22 23 24 25]
[ 0  0  0  0  0  0 26 27 28 29 30 31]

Padding with maxlen parameter :
[0 0 2 3 5 6]
[10 11 12 13 14 15]
[ 0  4 16 17 18 19]
[20 21 22 23 24 25]
[26 27 28 29 30 31]

Padding with maxlen & post_padding technique :
[2 3 5 6 0 0]
[10 11 12 13 14 15]
[ 4 16 17 18 19  0]
[20 21 22 23 24 25]
[26 27 28 29 30 31]

Padding with above two + truncating settings :
[2 3 5 6 0 0]
[2 3 7 8 4 9]
[ 4 16 17 18 19  0]
[20 21 22 23 24 25]
[26 27 28 29 30 31]


In [ ]:
# Since Our word_index dictionary contains a lot of stopwords which have no meaning in themselves and hence not required while doing NLP 

#Here is list of commonly used stopwords Rest you know how to exclude this words from Sentence using python !! (In case you don't know don't worry I will be doing that in upcoming Real World Example below)
Stopwords = ['a', 'about', 'above', 'after', 'again', 'against', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', 'not', 'as', 'at', 'be', 'because', 'been', 'before', 'being',\
             'below', 'between', 'both', 'but', 'by', 'can', 'not', 'cannot', 'could', 'couldn', 'not', 'did', 'didn', 'not', 'do', 'does', 'doesn', 'not', 'doing', 'don', 'not',\
             'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', 'not', 'has', 'hasn', 'not', 'have', 'haven', 'not', 'having', 'he', 'he', 'had', 'he', 'will',\
             'he', 'is', 'her', 'here', 'here', 'is', 'hers', 'herself', 'him', 'himself', 'his', 'how', 'how', 'is', 'i', 'i', 'had', 'i', 'will', 'i', 'am', 'i', 'have', 'if', 'in', \
             'into', 'is', 'isn', 'not', 'it', 'it', 'is', 'its', 'itself', 'let', 'is', 'me', 'more', 'most', 'mustn', 'not', 'my', 'myself', 'no', 'nor', 'not', 'of', 'off', 'on', 'once',\
             'only', 'or', 'other', 'ought', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 'same', 'shan', 'not', 'she', 'she', 'had', 'she', 'will', 'she', 'is', 'should', 'shouldn',\
             'not', 'so', 'some', 'such', 'than', 'that', 'that', 'is', 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'there', 'is', 'these', 'they', 'they', 'had', \
             'they', 'will', 'they', 'are', 'they', 'have', 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 'very', 'was', 'wasn', 'not', 'we', 'we', 'had', 'we', 'will',\
             'we', 'are', 'we', 'have', 'were', 'weren', 'not', 'what', 'what', 'is', 'when', 'when', 'is', 'where', 'where', 'is', 'which', 'while', 'who', 'who', 'is', 'whom', 'why',\
             'why', 'is', 'with', 'won', 'not', 'would', 'wouldn', 'not', 'you', 'you', 'had', 'you', 'will', 'you', 'are', 'you', 'have', 'your', 'yours', 'yourself', 'yourselves', 'MySQL', 'Stopw']

In [ ]:
# Second Common thing we encounter is that in real life people use shorthands like I've, I'am, we'll etc. etc. and Also there 
#could be  puncutation mark which are of  not use at all . To handle that scenerios , I have written these two functions

#To make shorhand like <I've> to their full form <I have > .These are some that I am familier with 
def clean_sentence(sentence):

  # A little bit sentence cleaning first to handle scenerio like his-her (note if dash is removed then 'hisher' is a nonsense word) by adding comma before and after such symbols . 
  sentence = sentence.replace('-',' - ')
  sentence = sentence.replace('.',' . ')
  sentence = sentence.replace('/',' / ')
  sentence = sentence.replace(',', ' , ')  # and so on.....as much as you like but these are a few common ones

  Words=sentence.split()
  sentence = ''
  for word in Words:
    word = word.replace("'s",' is')
    word = word.replace("'nt",' not')
    word = word.replace("n't",' not')
    word = word.replace("'d", ' had')
    word = word.replace("'ll",' will')
    word = word.replace("'m",' am')
    word = word.replace("'ve",' have')
    word = word.replace("'re", ' are')
    sentence = sentence + word + ' '
  return sentence 


#To remove the punctuation marks (if any) in sentences
def remove_punctuations(sentence):
  import string
  table = str.maketrans('','',string.punctuation)
  Words = sentence.split()
  sentence = ''
  for word in Words : 
    word = word.translate(table)
    sentence = sentence + word+ ' '
  return sentence


In [ ]:
## One last scenerio which comes in my mind is web_scrapping. In HTML codes there are syntax like <h>, <div> etc. which are of no use. To remove those there is a something called Beautiful Soap. 

#For example :-

html_code = """
            <!DOCTYPE html>
            <html>
            <body>

            <h1>My First Heading</h1>

            <p>My first paragraph.</p>

            </body>
            </html>
"""

from bs4 import BeautifulSoup
soup = BeautifulSoup(html_code)
sentence = soup.get_text()
print(sentence)

## With this we will now take up a Real World Data and Dirty our hands to make that data clean !! LETS GO---->



My First Heading
My first paragraph.





In [ ]:
#--------------------------------------------------------------------### A REAL WORLD EXMAPLE ####----------------------------------------------------------------------------------------------------------

In [ ]:
#Here we will use a  dataset available in tensorflow_datasets which is "IMDb" (Internet Movies Databases) containing various movies reviews and corresponding sentiment 'Good/Bad'
# We will only extract words which are present most frequently with some filtering techniques we know now
#Importing the dataset IMDb 

import tensorflow_datasets as tfds 
data = tfds.as_numpy(tfds.load('imdb_reviews',split='train'))

#In this dataset there are 50,000 reviews!!

In [ ]:
movie_reviews = []
for item in data : 
  review = str(item['text'].decode('UTF-8').lower())
  soup = BeautifulSoup(review)
  review = soup.get_text()
  review = clean_sentence(review)
  review = remove_punctuations(review)
  movie_reviews.append(review)

In [ ]:
movie_reviews[0]

'this was an absolutely terrible movie  do not be lured in by christopher walken or michael ironside  both are great actors  but this must simply be their worst role in history  even their great acting could not redeem this movie is ridiculous storyline  this movie is an early nineties us propaganda piece  the most pathetic scenes were those when the columbian rebels were making their cases for revolutions  maria conchita alonso appeared phony  and her pseudo  love affair with walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning  i am disappointed that there are movies like this  ruining actor is like christopher walken is good name  i could barely sit through it  '

In [ ]:
# Now do some tokenization and remove the stopwords from these cleaned sentences :>

# removing the stopwords from sentences 
updated = []
for review in movie_reviews : 
  sentence = ''
  review = review.split()
  for word in review : 
    if word not in Stopwords :    #This has been defined initially at the start You can go back  and check if you don't remember 
      sentence = sentence + word + ' '
  updated.append(sentence)
movie_reviews = updated 

#Tokenization 
tokenizer = Tokenizer(num_words=5000,oov_token='<oov>')
tokenizer.fit_on_texts(movie_reviews)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(movie_reviews)  # You can pass some other list of sentences here too to get their tokens. If some word in not present in word_index it will shows <oov>


In [ ]:
movie_reviews[0]  ## See yourself how many stopwords were there ....phww 

'absolutely terrible movie lured christopher walken michael ironside great actors must simply worst role history even great acting redeem movie ridiculous storyline movie early nineties us propaganda piece pathetic scenes columbian rebels making cases revolutions maria conchita alonso appeared phony pseudo love affair walken nothing pathetic emotional plug movie devoid real meaning disappointed movies like ruining actor like christopher walken good name barely sit '

In [ ]:
## Coverting sequences into rectangular matrix 

updated_sequences = pad_sequences(sequences,padding='post')
print('Shape of Matrix which will be fed in model : ',len(updated_sequences[0]),'x',len(updated_sequences))


#Note :
## This model can be futhur imporved by removing the words which have no meaning and are some random text , That we will see later.. Till then bye!

Shape of Matrix which will be fed in model :  1422 x 25000


In [ ]:
print('Some Top Words present in Reviews are :',list(word_index.keys())[1:20])  #IN decreasing order of frequency


Some Top Words present in Reviews are : ['movie', 'film', 'one', 'like', 'just', 'good', 'time', 'even', 'story', 'really', 'see', 'well', 'much', 'get', 'bad', 'people', 'also', 'great', 'first']


In [ ]:
# Decoder can be used convert these sequences back to review given except the text which was not recognized
Decoder = {}
for key,value in word_index.items():
  Decoder[value]=key


In [ ]:
## Lets give a review and see its sequence :
review = 'I saw that movie yesterday and I find that very boring still I find other way which is NLP very interesting lets solve some problems in that'
seq = tokenizer.texts_to_sequences([review])
print(seq)

[[1, 112, 1, 2, 3674, 1, 1, 71, 1, 1, 243, 46, 1, 71, 1, 22, 1, 1, 1, 1, 114, 1476, 3195, 1, 574, 1, 1]]


In [ ]:
decoded_sentence = ''
for x in seq[0] : 
  if x != 1:
    decoded_sentence = decoded_sentence + Decoder[x]+ ' '
print(decoded_sentence)

saw movie yesterday find boring still find way interesting lets solve problems 


### Reading JSON files and CSV files in python a

In [ ]:
#you can read csv files using pandas read_csv method . Simple isn't it? 
import pandas as pd 
data = pd.read_csv(r'ufo.csv')
data.head()

City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [ ]:
#Now if you want any column as training column lets say City column here then just select it like this

train = data['City'].tolist()
print(train[:10])

['Ithaca', 'Willingboro', 'Holyoke', 'Abilene', 'New York Worlds Fair', 'Valley City', 'Crater Lake', 'Alma', 'Eklutna', 'Hubbard']


In [53]:
#loading json file 
!wget --no-check-certificate \
    https://storage.googleapis.com/laurencemoroney-blog.appspot.com/sarcasm.json \
    -O /tmp/sarcasm.json

#Now we will see how to import JSON Files . pandas currently do not load JSON files directly . 
# for that we will use json library in python and make our life easier

import json

with open('/tmp/sarcasm.json','r') as f:
  data = json.load(f)

data[:5]


--2021-01-25 21:41:50--  https://storage.googleapis.com/laurencemoroney-blog.appspot.com/sarcasm.json
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.97.128, 74.125.134.128, 74.125.141.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.97.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5643545 (5.4M) [application/json]
Saving to: ‘/tmp/sarcasm.json’

/tmp/sarcasm.json   100%[===================>]   5.38M  --.-KB/s    in 0.03s   

2021-01-25 21:41:50 (165 MB/s) - ‘/tmp/sarcasm.json’ saved [5643545/5643545]



[{'article_link': 'https://www.huffingtonpost.com/entry/versace-black-code_us_5861fbefe4b0de3a08f600d5',
  'headline': "former versace store clerk sues over secret 'black code' for minority shoppers",
  'is_sarcastic': 0},
 {'article_link': 'https://www.huffingtonpost.com/entry/roseanne-revival-review_us_5ab3a497e4b054d118e04365',
  'headline': "the 'roseanne' revival catches up to our thorny political mood, for better and worse",
  'is_sarcastic': 0},
 {'article_link': 'https://local.theonion.com/mom-starting-to-fear-son-s-web-series-closest-thing-she-1819576697',
  'headline': "mom starting to fear son's web series closest thing she will have to grandchild",
  'is_sarcastic': 1},
 {'article_link': 'https://politics.theonion.com/boehner-just-wants-wife-to-listen-not-come-up-with-alt-1819574302',
  'headline': 'boehner just wants wife to listen, not come up with alternative debt-reduction ideas',
  'is_sarcastic': 1},
 {'article_link': 'https://www.huffingtonpost.com/entry/jk-rowling-w